language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: david.beale@bealearts.co.uk
  api_key:
    secure: WwfAh8Avw88VyCyV1ElqD9zqwq7RFgbBjRaUA5q3iZz8M12JJrPg99AaUUkQi6hjZg+VxmKGo4OVowrzTMxt2IVLPGasFQZIheTgbLTO7OCV0PkNuhdb8nhrs0TLezMzOZoH8E4ImRY0G9e3jUCfTC+PliaT/fhv5QhQDEJes7P13R9l95XnmsGUS1/JjNRg98bX8SpqQ1AWYF2LQkl+/rzZCS+I1TKeyb+z5hM/Y3Dx1tmjuHsS/wnacaI2S/8KRgDTg1ojSE1b8vPfLqB5iaKWWgwlJ9iX07BgdMIKNBC/rj5F3xCaw1e14B62IIMXoZcHX858COxhleDjJTRvcE9Iw4a8xb5iZA6EbGRtQ13AqAqV9bAmycX1wjHi49nNeqYxfJDZc1k+iiW7CBk4gP7clqaE9bX5npY41nhvB1YBlcUC6j6yPwLrLuF+vViCFssGF55/Y+mZOzGbuiUytmtpQPLej8adfbZnL9H91X7Vsq9X71Xc3lorrJ6Cz8Vnn7tdAIglkZ/7RH/uRTKeoOF7kEDyK8d3PS+jP/EBdXzqtLWntH1xaHjUjijp2W2c2ZTdN1i6o91v+qgsk4KhvCUTulsWV73rFdfdV6kjKA45vzxWdAShNQ6Bw2xTSXFZFx2axeVSLW4lLXpi3iWVMNFVOx/Cf1UKCsiO/AX7x10=
  on:
    all_branches: true
    tags: true
    repo: bealearts/poor-mans-proxy
