language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: david.beale@bealearts.co.uk
  api_key:
    secure: rUn77VG1RDhTHM8NrqctFKL+ljBIb00G7jaLV56SsSIri7EApow/Nu1HNLoe65kau9nT7jrMeMH1t34vPBRmegTvzv5AbkS0qyu5ZKQf+PWOHsXj9+pv+OcQFAqZKXWN6XnAhFXeAATxKokFrlvXUxkq8Vl7i3nl2OqIJZ4tamzpPK6zEnJXUoepUHfE3/kg4EPUAnhFDzXXRPAys6/xhjuHXKWNuWROh21sdCwlxCFKh0PcbSb8cFEcxkY7zdIYE1hUXVVi3cqS6GPPNo77zJiYC9Wc8UHtlVKLF3HRD8m0uJSCtL5jQFhVtcohLVEcM3LacVNVEdSzEZLLr9sN3KY7IdwdVfriU8JXe21DMtaUEoMr4XZ3pCrJAYCDgCvdxqmemkFcj/bxQL3mYoeS2VbnXK4BrCKxksVFs+UtMMjBAAMqTuzaHKTD7NslUj6DzorN4Roe0B2HjGrevZzD5nq59FdnjdqZq0/OqwXzc3bAPFLQvqME9B5++RV21uRJXBNcna0N9AUzRnD11i0d6AtGLuBPCXNDU7yL4c5bGM85FuQPBYLPzvUEbD1qMCeG3wc1s1Zug0CTzeO2BFItfDcgRhf1zza3TQtvtgRO6sDIeQ+0aYmZrGnQxJkIsoX1FbbhTfAOSWEjlaXwaLTd9aseXIy7jhGSQUjiLR68iOI=
  on:
    all_branches: true
    tags: true
    repo: bealearts/poor-mans-proxy
