language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  api_key:
    secure: Ne7Kh4276hovn/ZpVi9tHkN43bXsN2CGbULuoovmC4FxQQxB6vKSahgL28YB3TwXEhdtMGgfY5MPArT5FAeQSUsCJLhpReCcJEUQpu1a1374yoLIh8tVr3IoA8mcZ6LZJTS8zSNIPga/2b4AUP/tocsMomCkL1KQK7BKORAi/Nsp3WKCKC5sw7mGE18gAmW3CwKW7Mb41nBa03M/c3c+IDsK8GtrIQyTKXbYX1gHo0bfDvctYJaoTmXiQJ6fcnAY/lyvasxOU6eJ1sRzbajaq7EpuHOGV8NBcjP50SgTknwrtJULbZPCuON5+cB9BMGdbt0yLCAe9KQbsoaJax1ggNwuCp/92em8+HGfTY09f7QSJMtA48nMZMPh6UY+eFAGNyiMKXIN5oTvsL4OYqIeOzp9El0Asdg7uwmPW0DXf1GHHSb8eivH5Zq18lpGVSAQ1R/bu6Io+ZTkGcj5wgfKOdnmL3KzUyZowNC1Kfuc+Ld1CogsIxCRsPxCQrUsFYCurDmnUYcyWcwYjrHPtzbvMCr16t1nVhzqFNwubeRDI96mtMcSjQwGCiIIlAujYUQf5a9YkOA0oU3wJYtAeZ07jogKwmyL67qZy84lIAnKKpxmxEzd1N55gTprq1ijuTAt6ubJ+qIau/weHfY37f4J5IPIWlO6X78JQMIvLz6nLQ8=
  on:
    all_branches: true
    tags: true
    repo: bealearts/poor-mans-proxy
