language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: david.beale@bealearts.co.uk
  api_key:
    secure: LHJfWYFWsPDXeXqmcyeiEdXcUA+SmEeHO2hf0k0E9ZJ1f04TUF/v316JuYqrg8G8GY0abJKE2RDc/N9gqvzmFO8IgRN1kI3rcwyCMwQoFHcLtClf/oMKQjxXlkxHXscIS+HtUS7lM/nLZCBkSorcspID87l5ULU+Qz09AHSMLT0CNjSZxYu4WN+pRtEg9PvfoL1sXzkxVEkpFsKc652BcV4Gvpc5Du4EVq0c/W1wdWFsxlbANe8HIooaOTQDoUspvtqXDkGVQisqWVOhFpMMAoQl8QZ5bhtCX4YLKId1T9Qec93jQklFXQzNrN/RFI3e2coXztscRwp+Yh191xjpwOOgTmNtNKJD2545mKkWT5vVMksNfl2pW973orz4Ku+q+FIvCzEnIFIH0YHaQfswHkcEM7I4OFkPotxAEQYGEW6SHuElDfN4SWgQipNQliAiyKw+41Ykwq0hDVnHveN/XOEXuq6tBNf1mKkyjaTZNy6BUEV4RMupX5RjeWL2IAF1EUjv1CN6gQDsGSIvZzAJSX64d6OPbetiFwdzl8ERJryG+vDojV30+me6ndRSV7fGQzKo3iz7We0NooC6mjxI/X+2F9VRw4wjpbWfFKtfmOJpoFHBoODn2UARwRZgC7svUJ+ubgVkeQmdxYakqxazEwh7JMF2gqHUlFxbm7qFCxI=
  on:
    all_branches: true
    tags: true
    repo: bealearts/poor-mans-proxy
